### ISSUE TITLE
Oddly timed bridge in area 4 level 1

### ISSUE THREAD

**Issue by Hugheth** [Dizgruntled/Dizgruntled#29]
![Image](https://user-images.githubusercontent.com/271752/201468060-7eddd9b1-440c-4510-83e5-4d07c64d2bc5.png)

**Comment by Hugheth** [comment]
The underlying issue needs to be identified for this. Perhaps look at the internal time values used in Dizgruntled and compare with the WWD/ to the original / a walkthrough video to see what's up?

**Comment by tomalla5120x** [comment]
Possible cause: switching between browser tabs (quickly enough so the game doesn't pause in the meantime).
